----- DESHABILITAR EMPLEADO -----
CREATE OR REPLACE PROCEDURE DESHABILITAR_EMPLEADO(P_RUNEMPLEADO IN VARCHAR2) AS
BEGIN
    UPDATE  EMPLEADO
    SET     ESTADO = 0
    WHERE   RUNEMPLEADO = P_RUNEMPLEADO;
    COMMIT;
END;

--EXECUTE DESHABILITAR_EMPLEADO(20324243);