----- HABILITAR EMPLEADO -----
CREATE OR REPLACE PROCEDURE HABILITAR_EMPLEADO(P_RUNEMPLEADO IN VARCHAR2) AS
BEGIN
    UPDATE  EMPLEADO
    SET     ESTADO = 1
    WHERE   RUNEMPLEADO = P_RUNEMPLEADO;
    COMMIT;
END;

--EXECUTE HABILITAR_EMPLEADO(20324243);