-----LISTAR TODOS LOS EMPLEADOS-------
CREATE OR REPLACE PROCEDURE LISTARTODOSEMPLEADOS(C_MEMORIA OUT SYS_REFCURSOR)
AS
BEGIN 
  OPEN C_MEMORIA FOR SELECT EMP.ID, DIR.PASAJE, DIR.NUMERO, DIR.COMUNA, SUC.NOMBRES , EMP.ESTADO, EMP.RUNEMPLEADO, EMP.DIGITOVERIF, 
                            EMP.NOMBREE, EMP.APELLIDO,DIR.NUMERODEPTO,DIR.REGION,suc.TELEFONO,
                            emp.correoemple, EMP.CONTRASENA FROM EMPLEADO EMP
                            INNER JOIN DIRECCION DIR ON EMP.IDDIRECCION = DIR.ID 
                            LEFT JOIN SUCURSAL SUC ON EMP.IDSUCURSAL = SUC.ID;
END;

set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE LISTARTODOSEMPLEADOS(:C_MEMORIA);