-----LISTAR EMPLEADO-------
CREATE OR REPLACE PROCEDURE LISTAREMPLEADO(C_MEMORIA OUT SYS_REFCURSOR, P_RUNEMPLEADO IN VARCHAR2)
AS
BEGIN 
  OPEN C_MEMORIA FOR SELECT EMP.ID, DIR.PASAJE, DIR.NUMERO, DIR.COMUNA, SUC.NOMBRE , EMP.ESTADO, EMP.RUNEMPLEADO, EMP.DIGITOVERIF, 
                            EMP.NOMBRE, EMP.APELLIDO,
                            emp.correoemple, EMP.CONTRASENA FROM EMPLEADO EMP
                            INNER JOIN DIRECCION DIR ON EMP.IDDIRECCION = DIR.ID 
                            LEFT JOIN SUCURSAL SUC ON EMP.IDSUCURSAL = SUC.ID
                            WHERE RUNEMPLEADO = P_RUNEMPLEADO;
END;


--set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE LISTAREMPLEADO(:C_MEMORIA, '19513412');