-----LOGIN EMPLEADO-------
CREATE OR REPLACE PROCEDURE LOGIN_EMPLEADO(C_MEMORIA OUT SYS_REFCURSOR, P_CORREOEMPLE IN VARCHAR2, P_CONTRASENA IN VARCHAR2)
AS
BEGIN
    OPEN C_MEMORIA FOR SELECT CORREOEMPLE, CONTRASENA FROM EMPLEADO
                       WHERE CORREOEMPLE = P_CORREOEMPLE AND CONTRASENA = P_CONTRASENA;
END;

set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE LOGIN_EMPLEADO(:C_MEMORIA, 'f@gmail.com', 'admin');