----- AGREGAR PROVEEDOR -----
CREATE OR REPLACE PROCEDURE AGREGAR_PROVEEDOR(NEWRUNPROVEEDOR IN VARCHAR2, NEWDVPROVEEDOR IN VARCHAR2, NEWESTADO IN NUMBER, NEWNOMBRE IN VARCHAR2,
                                              NEWNUMEROTEL IN VARCHAR2, NEWDIRECCION IN VARCHAR2, NEWCORREO IN VARCHAR2)
AS
BEGIN
      INSERT INTO PROVEEDOR VALUES(AUIDPROVEEDOR.CURRVAL, AUIDEMPRESA.CURRVAL, NEWRUNPROVEEDOR, NEWDVPROVEEDOR, NEWESTADO, NEWNOMBRE, NEWNUMEROTEL, NEWDIRECCION, NEWCORREO);
END;

--EXECUTE AGREGAR_PROVEEDOR(332, 2, '18333222', '4', 1, 'ALAN BRITO', '999444333','LO BARNECHEA 321', 'ALBRIT@GMAIL.COM'); 