----- HABILITAR PROVEEDOR -----
CREATE OR REPLACE PROCEDURE HABILITAR_PROVEEDOR(P_RUNPROVEEDOR IN VARCHAR2) AS
BEGIN
    UPDATE  PROVEEDOR
    SET     ESTADO = 1
    WHERE   RUNPROVEEDOR = P_RUNPROVEEDOR;
    COMMIT;
END;

--EXECUTE HABILITAR_PROVEEDOR(17335987);
