----- LISTAR TODOS LOS PROVEEDORES -------
CREATE OR REPLACE PROCEDURE LISTARTODOSPROVEEDORES(C_MEMORIA OUT SYS_REFCURSOR)
AS
BEGIN 
  OPEN C_MEMORIA FOR SELECT PRO.ID, EM.RUTEMPRESA, EM.DVRUT, EM.NOMBTEEMPRESA, EM.CORREOEMP, EM.NUMEROTEL,
                            PRO.RUNPROVEEDOR, PRO.DIGITOVERIF, PRO.ESTADO, PRO.NOMBRE, PRO.NUMEROTEL, 
                            PRO.DIRECCION, PRO.CORREOPROV
                            FROM PROVEEDOR PRO INNER JOIN EMPRESA EM ON PRO.IDEMPRESA = EM.ID;                       
END;


set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE LISTARTODOSPROVEEDORES(:C_MEMORIA);