----LISTAR TODAS LAS ORDENES-----
create or replace PROCEDURE LISTARTODASORDENES(C_MEMORIA OUT SYS_REFCURSOR)
AS
BEGIN 
  OPEN C_MEMORIA FOR SELECT ORD.ID, SUC.ID, PROV.ID, ORD.FECHA, ORD.CANTIDAD
  							FROM ORDENESCOMPRA ORD
                            INNER JOIN PROVEEDOR PROV ON PROV.ID = ORD.IDPROVEEDOR
                            INNER JOIN SUCURSAL SUC ON SUC.ID = ORD.IDSUC;
END;

set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE LISTARTODASORDENES(:C_MEMORIA);