-----LISTAR ORDEN COMPRA-------
create or replace PROCEDURE LISTARORDEN(C_MEMORIA OUT SYS_REFCURSOR, P_IDORDEN IN VARCHAR2)
AS
BEGIN 
  OPEN C_MEMORIA FOR SELECT ORD.ID, SUC.NOMBRE, ORD.FECHA, ORD.CANTIDAD
                            FROM ORDENESCOMPRA ORD
                            INNER JOIN SUCURSAL SUC ON ORD.IDSUC = SUC.ID
                            WHERE ORD.ID = P_IDORDEN;
END;

--set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE LISTARORDEN(:C_MEMORIA, 1);