---AGREGAR VENTAS---
create or replace PROCEDURE AGREGAR_VENTAS(P_IDCLIENTE IN NUMBER, P_IDDETALLE IN NUMBER, 
                                           P_IDDOC IN NUMBER, P_IDRETIRO IN NUMBER, P_IDEMPLEADO IN NUMBER, 
                                           P_IDFORMAPAGO IN NUMBER, P_ESTADO IN NUMBER)
AS
BEGIN
	INSERT INTO VENTAS VALUES(AuidVENTAS.NEXTVAL, P_IDCLIENTE, P_IDDETALLE, P_IDDOC, P_IDRETIRO, P_IDEMPLEADO, P_IDFORMAPAGO, P_ESTADO);
END;