---------LISTAR TODAS LAS VENTAS---------
create or replace PROCEDURE LISTARTODASVENTAS(C_MEMORIA OUT SYS_REFCURSOR)
AS
BEGIN 
  OPEN C_MEMORIA FOR SELECT VEN.ID, CLI.ID, DET.IDDETALLE, DOC.ID, RET.IDRETIRO, EMP.ID, FORM.ID, VEN.ESTADO
  							FROM VENTAS VEN
                            INNER JOIN CLIENTE CLI ON CLI.ID = VEN.IDCLIENTE
                            INNER JOIN DETALLEVENTA DET ON DET.IDDETALLE = VEN.IDDETALLE
                            INNER JOIN DOCUMENTO DOC ON DOC.ID = VEN.IDDOC
                            INNER JOIN RETIRO RET ON RET.IDRETIRO = VEN.IDRETIRO
                            INNER JOIN EMPLEADO EMP ON EMP.ID = VEN.IDEMPLEADO
                            INNER JOIN FORMADEPAGO FORM ON FORM.ID = VEN.IDFORMAPAGO;
END;

set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE LISTARTODASVENTAS(:C_MEMORIA);