---------LISTAR VENTA POR RUN---------
create or replace PROCEDURE LISTARVENTARUN(C_MEMORIA OUT SYS_REFCURSOR, P_RUN IN NUMBER)
AS
BEGIN 
  OPEN C_MEMORIA FOR SELECT VEN.ID, CLI.RUNCLIENTE, CLI.NOMBRE || ' ' || CLI.APELLIDO AS NOMBRE, DET.FECHACOMPRA, DET.TOTAL FROM VENTAS VEN
                            INNER JOIN CLIENTE CLI ON VEN.IDCLIENTE = CLI.ID
                            LEFT JOIN DETALLEVENTA DET ON VEN.IDDETALLE = DET.IDDETALLE
                            WHERE CLI.RUNCLIENTE = P_RUN;
END;
set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE LISTARVENTA(:C_MEMORIA, 2);