----- HABILITAR SUCURSAL -----
CREATE OR REPLACE PROCEDURE HABILITAR_SUCURSAL(P_ID IN NUMBER) AS
BEGIN
    UPDATE  SUCURSAL
    SET     ESTADO = 1
    WHERE   ID = P_ID;
    COMMIT;
END;

--EXECUTE HABILITAR_SUCURSAL(30);