----LISTAR TODOS LAS SUCURSALES-----
create or replace PROCEDURE LISTARTODASSUCURSALES(C_MEMORIA OUT SYS_REFCURSOR)
AS
BEGIN 
  OPEN C_MEMORIA FOR SELECT SUC.ID, SUC.NOMBRE, SUC.TELEFONO
  							FROM SUCURSAL SUC;
END;


set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE LISTARTODASSUCURSALES(:C_MEMORIA);