-----LISTAR SUCURSAL-------
CREATE OR REPLACE PROCEDURE LISTARSUCURSAL(C_MEMORIA OUT SYS_REFCURSOR, P_IDSUCURSAL IN VARCHAR2)
AS
BEGIN 
  OPEN C_MEMORIA FOR SELECT SUC.ID, SUC.NOMBRE, SUC.TELEFONO
  							FROM SUCURSAL SUC
                            WHERE ID = P_IDSUCURSAL;
END;

set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE LISTARSUCURSAL(:C_MEMORIA, 1);