----- AGREGAR DETALLE VENTA -----
CREATE OR REPLACE PROCEDURE AGREGAR_DETALLE_VENTA( P_IDPRODUCTO IN NUMBER, P_FECHACOMPRA IN VARCHAR2, P_CANTIDAD IN NUMBER, P_TOTAL IN NUMBER)
AS
BEGIN
	INSERT INTO DETALLEVENTA VALUES(AuidDETALLEVENTA.NEXTVAL, P_IDPRODUCTO, P_FECHACOMPRA, P_CANTIDAD, P_TOTAL);
END;

--EXECUTE AGREGAR_DETALLE_VENTA(1, '22-02-2020', 2, 10000);