----LISTAR TODOS LOS DETALLES DE UNA VENTA-----
CREATE OR REPLACE PROCEDURE LISTARTODOSDETALLESVENTAS(C_MEMORIA OUT SYS_REFCURSOR)
AS
BEGIN 
  OPEN C_MEMORIA FOR SELECT DET.IDDETALLE, PRO.ID, DET.FECHACOMPRA, DET.CANTIDAD, DET.TOTAL  FROM DETALLEVENTA DET
                            INNER JOIN PRODUCTO PRO ON DET.IDPRODUCTO = PRO.ID;  
                            
END;


set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE LISTARTODOSDETALLESVENTAS(:C_MEMORIA);