----- ACTUALIZAR PRECIO PRODUCTO -----
CREATE OR REPLACE PROCEDURE ACTUALIZAR_PRECIO_PRODUCTO(P_ID IN NUMBER, P_PRECIOUNI IN NUMBER)
AS
BEGIN
	UPDATE PRODUCTO 
	SET PRECIOUNI = P_PRECIOUNI
	WHERE ID = P_ID;
END;

--EXECUTE ACTUALIZAR_PRECIO_PRODUCTO(1, 3990);