----- ACTUALIZAR STOCK PRODUCTO -----
CREATE OR REPLACE PROCEDURE ACTUALIZAR_STOCK_PRODUCTO(P_ID IN NUMBER, P_STOCK IN NUMBER)
AS
BEGIN
	UPDATE PRODUCTO 
	SET STOCK = P_STOCK
	WHERE ID = P_ID;
END;

--EXECUTE ACTUALIZAR_STOCK_PRODUCTO(1, 999);