----- AGREGAR PRODUCTO ----- 
CREATE OR REPLACE PROCEDURE AGREGAR_PRODUCTO(P_IDTIPOPRODUCTO IN NUMBER, P_IDSUCURSAL IN NUMBER, P_IDPROVEEDOR IN NUMBER, 
	                                         P_NOMBRE IN VARCHAR2, P_STOCK IN NUMBER, P_PRECIOUNI IN NUMBER)
AS
BEGIN
	INSERT INTO PRODUCTO VALUES(AUIDPRODUCTO.CURRVAL, P_IDTIPOPRODUCTO, P_IDSUCURSAL, P_IDPROVEEDOR, P_NOMBRE, P_STOCK, P_PRECIOUNI);
END;

--EXECUTE AGREGAR_PRODUCTO(1, 1, 1, 'Serrucho', 20, 4990);