----- DESHABILITAR PRODUCTO -----
CREATE OR REPLACE PROCEDURE DESHABILITAR_PRODUCTO(P_ID IN NUMBER) AS
BEGIN
    UPDATE  PRODUCTO
    SET     ESTADO = 0
    WHERE   ID = P_ID;
    COMMIT;
END;

--EXECUTE DESHABILITAR_PRODUCTO(311);