----LISTAR TODOS LOS PRODUCTOS-----
CREATE OR REPLACE PROCEDURE LISTARTODOSPRODUCTOS(C_MEMORIA OUT SYS_REFCURSOR)
AS
BEGIN 
  OPEN C_MEMORIA FOR SELECT PRO.ID, PRO.IDTIPOPRODUCTO, PRO.IDSUCURSAL, PRO.IDPROVEEDOR, PRO.NOMBRE, PRO.STOCK, PRO.PRECIOUNI 
  							FROM PRODUCTO PRO
                            INNER JOIN PROVEEDOR PROV ON PRO.IDPROVEEDOR = PROV.ID
                            INNER JOIN SUCURSAL SUC ON PRO.IDSUCURSAL = SUC.ID
                            INNER JOIN TIPOPRODUCTO TPRO ON PRO.IDTIPOPRODUCTO = TPRO.ID;
                            
END;

set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE LISTARTODOSPRODUCTOS(:C_MEMORIA);