----- LISTAR DOCUMENTOS -------
CREATE OR REPLACE PROCEDURE LISTARDOCUMENTO(C_MEMORIA OUT SYS_REFCURSOR, P_NUMFOLIO IN NUMBER)
AS
BEGIN 
  OPEN C_MEMORIA FOR SELECT DOC.ID, TIPD.NOMBRE, DOC.NUMFOLIO, DOC.FECHA
                            FROM DOCUMENTO DOC INNER JOIN TIPODOCUMENTO TIPD ON DOC.TIPODOC = TIPD.ID
                            WHERE NUMFOLIO = P_NUMFOLIO;                  
END;


set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE LISTARDOCUMENTO(:C_MEMORIA, 14515151);
