----- LISTAR TODOS LOS DOCUMENTOS -------
CREATE OR REPLACE PROCEDURE LISTARTODOSDOCUMENTOS(C_MEMORIA OUT SYS_REFCURSOR)
AS
BEGIN 
  OPEN C_MEMORIA FOR SELECT DOC.ID, TIPD.NOMBRE, DOC.NUMFOLIO, DOC.FECHA
                            FROM DOCUMENTO DOC INNER JOIN TIPODOCUMENTO TIPD ON DOC.TIPODOC = TIPD.ID;                
END;



set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE LISTARTODOSDOCUMENTOS(:C_MEMORIA);