----- ACTUALIZAR CORREO CLIENTE -----
CREATE OR REPLACE PROCEDURE ACTUALIZAR_CORREO_CLIENTE(P_RUNCLIENTE IN VARCHAR2, NEWCORREO IN VARCHAR2)
AS
BEGIN
  UPDATE CLIENTE SET CORREO= NEWCORREO
  WHERE RUNCLIENTE = P_RUNCLIENTE;
END;

--EXECUTE ACTUALIZAR_CORREO_CLIENTE('12423531', 'PERROBOMBA@GMAIL.COM');