----- ACTUALIZAR CORREO PROVEEDOR -----
CREATE OR REPLACE PROCEDURE ACTUALIZAR_CORREO_PROVEEDOR(P_RUNPROVEEDOR IN VARCHAR2, P_CORREO IN VARCHAR2)
AS
BEGIN
	UPDATE PROVEEDOR 
	SET CORREO = P_CORREO
	WHERE RUNPROVEEDOR = P_RUNPROVEEDOR;
END;

--EXECUTE ACTUALIZAR_CORREO_PROVEEDOR('17335987', 'OYEREQUEST@GMAIL.COM')