----- ACTUALIZAR NOMBRE SUCURSAL -----
CREATE OR REPLACE PROCEDURE ACTUALIZAR_NOMBRE_SUCURSAL(P_ID IN NUMBER, P_NOMBRE IN VARCHAR2)
AS
BEGIN
	UPDATE SUCURSAL 
	SET NOMBRE = P_NOMBRE
	WHERE ID = P_ID;
END;

--EXECUTE ACTUALIZAR_NOMBRE_SUCURSAL(1, 'FERME Cubillos');