----- ACTUALIZAR CORREO EMPLEADO -----
CREATE OR REPLACE PROCEDURE ACTUALIZAR_CORREO_EMPLEADO(P_RUNEMPLEADO IN VARCHAR2, P_CORREO IN VARCHAR2)
AS
BEGIN
	UPDATE EMPLEADO 
	SET CORREO = P_CORREO
	WHERE RUNEMPLEADO = P_RUNEMPLEADO;
END;

--EXECUTE ACTUALIZAR_CORREO_EMPLEADO('20324243', 'EL_COLITA@GMAIL.COM');