----- DESHABILITAR CLIENTE -----
CREATE OR REPLACE PROCEDURE DESHABILITAR_CLIENTE(P_RUNCLIENTE IN VARCHAR2) AS
BEGIN
    UPDATE  CLIENTE
    SET     ESTADO = 0
    WHERE   RUNCLIENTE=P_RUNCLIENTE;
    COMMIT;
END;

--EXECUTE DESHABILITAR_CLIENTE(12423531);
