----- ACTUALIZAR CONTRASEÑA CLIENTE -----
CREATE OR REPLACE PROCEDURE ACTUALIZAR_CONTRASENA_CLIENTE(P_RUNCLIENTE IN VARCHAR2, NEWCONTRASENA IN VARCHAR2)
AS
BEGIN
  UPDATE CLIENTE SET CONTRASENA= NEWCONTRASENA
  WHERE RUNCLIENTE = P_RUNCLIENTE;
END;

--EXECUTE ACTUALIZAR_CONTRASENA_CLIENTE('12423531', '12345');