----- AGREGAR CLIENTE -----
CREATE OR REPLACE PROCEDURE AGREGAR_CLIENTE(NEWIDDIRECCION IN NUMBER, NEWRUN IN VARCHAR2, NEWDIGITOVERIF IN VARCHAR2, NEWESTADO IN NUMBER,
                                             NEWNOMBRE IN VARCHAR2, NEWAPELLIDO IN VARCHAR2, NEWSEXO IN NUMBER, NEWCORREO IN VARCHAR2, NEWCONTRASENA IN VARCHAR2)
AS
BEGIN
	INSERT INTO CLIENTE VALUES(AUIDCLIENTE.CURRVAL,NEWIDDIRECCION, NEWRUN, NEWDIGITOVERIF, NEWESTADO, NEWNOMBRE, NEWAPELLIDO, NEWSEXO, NEWCORREO, NEWCONTRASENA);
END;

--EXECUTE AGREGAR_CLIENTE(2,'11121222','1', 1, 'JUAN', 'CACTILIO', 1, 'JCACTILIO@GMAIL.COM', '1234');