----- HABILITAR CLIENTE -----
  CREATE OR REPLACE PROCEDURE HABILITAR_CLIENTE (P_RUNCLIENTE IN VARCHAR2) AS
BEGIN
    UPDATE  CLIENTE
    SET     ESTADO = 1
    WHERE   RUNCLIENTE=P_RUNCLIENTE;
    COMMIT;
END;


