-----LISTAR CLIENTE-------
CREATE OR REPLACE PROCEDURE LISTARCLIENTES(C_MEMORIA OUT SYS_REFCURSOR, P_RUNCLIENTE IN VARCHAR2)
AS
BEGIN 
  OPEN C_MEMORIA FOR SELECT CLI.ID, DIR.PASAJE, DIR.NUMERO, DIR.COMUNA, CLI.RUNCLIENTE, CLI.DIGITOVERIF, CLI.ESTADO, CLI.NOMBRE, CLI.APELLIDO,
                            CLI.CORREOCLI, CLI.CONTRASENA FROM CLIENTE CLI
                            INNER JOIN DIRECCION DIR ON CLI.IDDIRECCION = DIR.ID  
                            WHERE RUNCLIENTE = P_RUNCLIENTE;
END;


set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE listarClientes(:C_MEMORIA, '12423531');