----LISTAR TODOS LOS CLIENTES-----
CREATE OR REPLACE PROCEDURE LISTARTODOSCLIENTES(C_MEMORIA OUT SYS_REFCURSOR)
AS
BEGIN 
  OPEN C_MEMORIA FOR SELECT CLI.ID, CLI.RUNCLIENTE, CLI.DIGITOVERIF, CLI.ESTADO, CLI.NOMBRE,                             CLI.APELLIDO, DIR.PASAJE, DIR.NUMERO, DIR.COMUNA, DIR.REGION,
                            CLI.CORREO, CLI.CONTRASENA FROM CLIENTE CLI
                            INNER JOIN DIRECCION DIR ON CLI.IDDIRECCION = DIR.ID;  
                            
END;


set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE listartodosclientes(:C_MEMORIA);