-----LOGIN CLIENTE-------
CREATE OR REPLACE PROCEDURE LOGIN_CLIENTE(C_MEMORIA OUT SYS_REFCURSOR, P_CORREOCLI IN VARCHAR2, P_CONTRASENA IN VARCHAR2)
AS
BEGIN
    OPEN C_MEMORIA FOR SELECT CORREOCLI, CONTRASENA FROM CLIENTE
                       WHERE CORREOCLI = P_CORREOCLI AND CONTRASENA = P_CONTRASENA;
END;

set autoprint on;
--VARIABLE C_MEMORIA REFCURSOR;
--EXECUTE LOGIN_CLIENTE(:C_MEMORIA, 'Juan@gmail.com', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918');